name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create report file
      run: date +%s > report.txt
    - name: Commit Change
      run: |
        git config --local user.email "mszhanyi@user.noreply.github.com"
        git config --local user.name "mszhanyi"     
        git add report.txt
        git commit -m "commit change"
        echo ${{ github.ref }}
    - name: Push report
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: mszhanyi/pytorch
        persist-credentials: false
        path: pytorch
        fetch-depth: 0
    - name: sync with upstream
      run: |
        cd pytorch
        git config --local user.email "mszhanyi@user.noreply.github.com"
        git config --local user.name "mszhanyi"
        git status
        git remote add upstream https://github.com/pytorch/pytorch
        git remote -v
        git fetch upstream
        git merge upstream/master
        git status
    - name: Logging
      run: |
        pwd
        cd pytorch 
        echo ${GITHUB_REPOSITORY}
    - name: Push report
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.aiinfra-linux2 }}
        repository: mszhanyi/pytorch
        directory: ./pytorch
    - name: Install and Build
      run: |
        npm install
        npm run-script build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.demos }}
        BRANCH: gh-pages
        FOLDER: build
