name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
  #schedule:
  #  - cron: '* * 1/1 * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      pytorch_token: ${{secrets.PYTORCH_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Checkout Pytorch
      uses: actions/checkout@v2
      with:
        repository: mszhanyi/pytorch
        persist-credentials: false
        path: pytorch
        fetch-depth: 0
    - name: sync with upstream
      working-directory: ./scripts
      run: |
        bash syncmaster.sh
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{secrets.PYTORCH_KEY}}
        commit-message: Update report
        commiter: GitHub <noreply@github.com>
        author: mszhanyi
        signoff: false
        repository: mszhanyi/pytorch
        branch: updatevcver
        delete-branch: true
        title: '[Tesing] Submit one PR'

