name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
  #schedule:
  #  - cron: '* * 1/1 * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: mszhanyi/pytorch
        persist-credentials: false
        path: pytorch
        fetch-depth: 0
    - name: sync with upstream
      run: |
        ./syncmaster.sh
